<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-05-23 14:53
=======
# Generated by Django 2.0.5 on 2018-05-17 11:55
>>>>>>> grade

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('number', models.CharField(max_length=10)),
=======
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=200)),
>>>>>>> grade
            ],
        ),
    ]
