# Generated by Django 2.0.5 on 2018-05-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
    ]
