# Generated by Django 2.0.5 on 2018-05-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcademicYear', models.IntegerField()),
                ('Semester', models.IntegerField()),
                ('Code', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('ClassField', models.CharField(max_length=200)),
                ('credit', models.IntegerField()),
                ('Remark', models.CharField(max_length=200)),
            ],
        ),
    ]
