# Generated by Django 2.0.5 on 2018-05-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credit',
            new_name='Credit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='Code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='Name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
