# Generated by Django 2.0.5 on 2018-05-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20180518_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Student_Belong',
            field=models.ManyToManyField(to='mainsite.Student'),
        ),
    ]
