# Generated by Django 2.0.5 on 2018-05-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_department_student_belong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
                ('GPA', models.IntegerField()),
                ('Course_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Course')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Student')),
            ],
        ),
    ]
