# Generated by Django 2.0.5 on 2018-05-18 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20180518_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField(default=-1)),
                ('GPA', models.IntegerField(default=-1)),
                ('Course_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Course')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='studies',
            name='Course_Code',
        ),
        migrations.RemoveField(
            model_name='studies',
            name='Student_ID',
        ),
        migrations.DeleteModel(
            name='Studies',
        ),
    ]
